# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortner', '0004_auto_20170314_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('chota_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortner.ChotaURL')),
            ],
        ),
    ]
