# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChotaURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220, unique=True)),
                ('shortcode', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
