# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chotaurl',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
