# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_chotaurl_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chotaurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chotaurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
